version: '3'

networks:
  medialib-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

services:
  medialib:
    build:
      context: .
      dockerfile: ./medialib/Dockerfile
    ports:
      - "127.0.0.1:9001:9001" 
      - "127.0.0.1:6600:6600"
    depends_on:
      - webui 
    restart: on-failure
    networks:
      medialib-net
      ipv4_address: 172.28.0.10
  webui:
    build:
      context: .
      dockerfile: ./www/Dockerfile
    
    ports:
      - "127.0.0.1:80:80"
      
    restart: on-failure
    networks:
      medialib-net
      ipv4_address: 172.28.0.10
