version: '3'
services:
  medialib:
    build:
      context: .
      dockerfile: ./medialib/Dockerfile
    volumes:
      - log:/home/medialib/MediaLibManager/log
    ports:
      - "127.0.0.1:9001:9001" 
      - "127.0.0.1:6600:6600"
    depends_on:
      - webui 
    restart: on-failure
  webui:
    build:
      context: .
      dockerfile: ./www/Dockerfile
    volumes:
      - log:/home/medialib/MediaLibManager/log
    ports:
      - "127.0.0.1:80:80"
      
    restart: on-failure
  volumes:
      log
