version: '3'
services:
  medialib:
    build:
      context: .
      dockerfile: ./medialib/Dockerfile
    volumes:
      - log:/home/medialib/MediaLibManager/log
      - db:/home/medialib/MediaLibManager/db
    ports:
      - "9001:9001" 
      - "6600:6600"
    depends_on:
      - webui 
    restart: on-failure
  webui:
    build:
      context: .
      dockerfile: ./www/Dockerfile
    volumes:
      - log:/home/medialib/MediaLibManager/log
    ports:
      - "80:80"   
    restart: on-failure
volumes:
   log:
   db:
