[project]
name='MediaLibManager'
version='2.9.10'
description='Music metadata managing, navigation and playing Service'
requires-python = ">=3.7"
dynamic = ["version"]
dependencies = [
    "mutagen",
    "chardet",
    'importlib-metadata>="3.7"'
]

